//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Prism.ExternalService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://www.severfield.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[][]))]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthHeader authHeaderValueField;
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback WriteToSpecificLineOperationCompleted;
        
        private System.Threading.SendOrPostCallback WriteAllLinesWithArrayOperationCompleted;
        
        private System.Threading.SendOrPostCallback WriteAppendStringToFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback WriteAppendStringsToFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadSpecificLineOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadAllLinesIntoArrayOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDirectoriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback DirectoryExistsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDirectoryNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback DirectoryGetFilesOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateDirectoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback FileExistsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateNewDirectoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback WriteToExcelOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadFromExcelOperationCompleted;
        
        private System.Threading.SendOrPostCallback WriteToExcelRangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadFromExcelRangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateNewExcelSheetOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::Prism.Properties.Settings.Default.Prism_ExternalService_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthHeader AuthHeaderValue {
            get {
                return this.authHeaderValueField;
            }
            set {
                this.authHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event WriteToSpecificLineCompletedEventHandler WriteToSpecificLineCompleted;
        
        /// <remarks/>
        public event WriteAllLinesWithArrayCompletedEventHandler WriteAllLinesWithArrayCompleted;
        
        /// <remarks/>
        public event WriteAppendStringToFileCompletedEventHandler WriteAppendStringToFileCompleted;
        
        /// <remarks/>
        public event WriteAppendStringsToFileCompletedEventHandler WriteAppendStringsToFileCompleted;
        
        /// <remarks/>
        public event ReadSpecificLineCompletedEventHandler ReadSpecificLineCompleted;
        
        /// <remarks/>
        public event ReadAllLinesIntoArrayCompletedEventHandler ReadAllLinesIntoArrayCompleted;
        
        /// <remarks/>
        public event GetDirectoriesCompletedEventHandler GetDirectoriesCompleted;
        
        /// <remarks/>
        public event DirectoryExistsCompletedEventHandler DirectoryExistsCompleted;
        
        /// <remarks/>
        public event GetDirectoryNameCompletedEventHandler GetDirectoryNameCompleted;
        
        /// <remarks/>
        public event DirectoryGetFilesCompletedEventHandler DirectoryGetFilesCompleted;
        
        /// <remarks/>
        public event CreateDirectoryCompletedEventHandler CreateDirectoryCompleted;
        
        /// <remarks/>
        public event FileExistsCompletedEventHandler FileExistsCompleted;
        
        /// <remarks/>
        public event CreateNewDirectoryCompletedEventHandler CreateNewDirectoryCompleted;
        
        /// <remarks/>
        public event WriteToExcelCompletedEventHandler WriteToExcelCompleted;
        
        /// <remarks/>
        public event ReadFromExcelCompletedEventHandler ReadFromExcelCompleted;
        
        /// <remarks/>
        public event WriteToExcelRangeCompletedEventHandler WriteToExcelRangeCompleted;
        
        /// <remarks/>
        public event ReadFromExcelRangeCompletedEventHandler ReadFromExcelRangeCompleted;
        
        /// <remarks/>
        public event CreateNewExcelSheetCompletedEventHandler CreateNewExcelSheetCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.severfield.com/HelloWorld", RequestNamespace="http://www.severfield.com/", ResponseNamespace="http://www.severfield.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.severfield.com/WriteToSpecificLine", RequestNamespace="http://www.severfield.com/", ResponseNamespace="http://www.severfield.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool WriteToSpecificLine(int filePathLine, int lineToWriteTo, string content, string additionalPath) {
            object[] results = this.Invoke("WriteToSpecificLine", new object[] {
                        filePathLine,
                        lineToWriteTo,
                        content,
                        additionalPath});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void WriteToSpecificLineAsync(int filePathLine, int lineToWriteTo, string content, string additionalPath) {
            this.WriteToSpecificLineAsync(filePathLine, lineToWriteTo, content, additionalPath, null);
        }
        
        /// <remarks/>
        public void WriteToSpecificLineAsync(int filePathLine, int lineToWriteTo, string content, string additionalPath, object userState) {
            if ((this.WriteToSpecificLineOperationCompleted == null)) {
                this.WriteToSpecificLineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWriteToSpecificLineOperationCompleted);
            }
            this.InvokeAsync("WriteToSpecificLine", new object[] {
                        filePathLine,
                        lineToWriteTo,
                        content,
                        additionalPath}, this.WriteToSpecificLineOperationCompleted, userState);
        }
        
        private void OnWriteToSpecificLineOperationCompleted(object arg) {
            if ((this.WriteToSpecificLineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WriteToSpecificLineCompleted(this, new WriteToSpecificLineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.severfield.com/WriteAllLinesWithArray", RequestNamespace="http://www.severfield.com/", ResponseNamespace="http://www.severfield.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void WriteAllLinesWithArray(int filePathLine, string[] content, string addtionalPath) {
            this.Invoke("WriteAllLinesWithArray", new object[] {
                        filePathLine,
                        content,
                        addtionalPath});
        }
        
        /// <remarks/>
        public void WriteAllLinesWithArrayAsync(int filePathLine, string[] content, string addtionalPath) {
            this.WriteAllLinesWithArrayAsync(filePathLine, content, addtionalPath, null);
        }
        
        /// <remarks/>
        public void WriteAllLinesWithArrayAsync(int filePathLine, string[] content, string addtionalPath, object userState) {
            if ((this.WriteAllLinesWithArrayOperationCompleted == null)) {
                this.WriteAllLinesWithArrayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWriteAllLinesWithArrayOperationCompleted);
            }
            this.InvokeAsync("WriteAllLinesWithArray", new object[] {
                        filePathLine,
                        content,
                        addtionalPath}, this.WriteAllLinesWithArrayOperationCompleted, userState);
        }
        
        private void OnWriteAllLinesWithArrayOperationCompleted(object arg) {
            if ((this.WriteAllLinesWithArrayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WriteAllLinesWithArrayCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.severfield.com/WriteAppendStringToFile", RequestNamespace="http://www.severfield.com/", ResponseNamespace="http://www.severfield.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void WriteAppendStringToFile(int filePathLine, string content, string additionalPath) {
            this.Invoke("WriteAppendStringToFile", new object[] {
                        filePathLine,
                        content,
                        additionalPath});
        }
        
        /// <remarks/>
        public void WriteAppendStringToFileAsync(int filePathLine, string content, string additionalPath) {
            this.WriteAppendStringToFileAsync(filePathLine, content, additionalPath, null);
        }
        
        /// <remarks/>
        public void WriteAppendStringToFileAsync(int filePathLine, string content, string additionalPath, object userState) {
            if ((this.WriteAppendStringToFileOperationCompleted == null)) {
                this.WriteAppendStringToFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWriteAppendStringToFileOperationCompleted);
            }
            this.InvokeAsync("WriteAppendStringToFile", new object[] {
                        filePathLine,
                        content,
                        additionalPath}, this.WriteAppendStringToFileOperationCompleted, userState);
        }
        
        private void OnWriteAppendStringToFileOperationCompleted(object arg) {
            if ((this.WriteAppendStringToFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WriteAppendStringToFileCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.severfield.com/WriteAppendStringsToFile", RequestNamespace="http://www.severfield.com/", ResponseNamespace="http://www.severfield.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void WriteAppendStringsToFile(int filePathLine, string[] content, string additionalPath) {
            this.Invoke("WriteAppendStringsToFile", new object[] {
                        filePathLine,
                        content,
                        additionalPath});
        }
        
        /// <remarks/>
        public void WriteAppendStringsToFileAsync(int filePathLine, string[] content, string additionalPath) {
            this.WriteAppendStringsToFileAsync(filePathLine, content, additionalPath, null);
        }
        
        /// <remarks/>
        public void WriteAppendStringsToFileAsync(int filePathLine, string[] content, string additionalPath, object userState) {
            if ((this.WriteAppendStringsToFileOperationCompleted == null)) {
                this.WriteAppendStringsToFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWriteAppendStringsToFileOperationCompleted);
            }
            this.InvokeAsync("WriteAppendStringsToFile", new object[] {
                        filePathLine,
                        content,
                        additionalPath}, this.WriteAppendStringsToFileOperationCompleted, userState);
        }
        
        private void OnWriteAppendStringsToFileOperationCompleted(object arg) {
            if ((this.WriteAppendStringsToFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WriteAppendStringsToFileCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.severfield.com/ReadSpecificLine", RequestNamespace="http://www.severfield.com/", ResponseNamespace="http://www.severfield.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReadSpecificLine(int filePathLine, int lineToRead, string additionalPath) {
            object[] results = this.Invoke("ReadSpecificLine", new object[] {
                        filePathLine,
                        lineToRead,
                        additionalPath});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReadSpecificLineAsync(int filePathLine, int lineToRead, string additionalPath) {
            this.ReadSpecificLineAsync(filePathLine, lineToRead, additionalPath, null);
        }
        
        /// <remarks/>
        public void ReadSpecificLineAsync(int filePathLine, int lineToRead, string additionalPath, object userState) {
            if ((this.ReadSpecificLineOperationCompleted == null)) {
                this.ReadSpecificLineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadSpecificLineOperationCompleted);
            }
            this.InvokeAsync("ReadSpecificLine", new object[] {
                        filePathLine,
                        lineToRead,
                        additionalPath}, this.ReadSpecificLineOperationCompleted, userState);
        }
        
        private void OnReadSpecificLineOperationCompleted(object arg) {
            if ((this.ReadSpecificLineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadSpecificLineCompleted(this, new ReadSpecificLineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.severfield.com/ReadAllLinesIntoArray", RequestNamespace="http://www.severfield.com/", ResponseNamespace="http://www.severfield.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ReadAllLinesIntoArray(int filePathLine, string additionalPath) {
            object[] results = this.Invoke("ReadAllLinesIntoArray", new object[] {
                        filePathLine,
                        additionalPath});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadAllLinesIntoArrayAsync(int filePathLine, string additionalPath) {
            this.ReadAllLinesIntoArrayAsync(filePathLine, additionalPath, null);
        }
        
        /// <remarks/>
        public void ReadAllLinesIntoArrayAsync(int filePathLine, string additionalPath, object userState) {
            if ((this.ReadAllLinesIntoArrayOperationCompleted == null)) {
                this.ReadAllLinesIntoArrayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadAllLinesIntoArrayOperationCompleted);
            }
            this.InvokeAsync("ReadAllLinesIntoArray", new object[] {
                        filePathLine,
                        additionalPath}, this.ReadAllLinesIntoArrayOperationCompleted, userState);
        }
        
        private void OnReadAllLinesIntoArrayOperationCompleted(object arg) {
            if ((this.ReadAllLinesIntoArrayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadAllLinesIntoArrayCompleted(this, new ReadAllLinesIntoArrayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.severfield.com/GetDirectories", RequestNamespace="http://www.severfield.com/", ResponseNamespace="http://www.severfield.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetDirectories(int filePathLine, string additionalPath) {
            object[] results = this.Invoke("GetDirectories", new object[] {
                        filePathLine,
                        additionalPath});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDirectoriesAsync(int filePathLine, string additionalPath) {
            this.GetDirectoriesAsync(filePathLine, additionalPath, null);
        }
        
        /// <remarks/>
        public void GetDirectoriesAsync(int filePathLine, string additionalPath, object userState) {
            if ((this.GetDirectoriesOperationCompleted == null)) {
                this.GetDirectoriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDirectoriesOperationCompleted);
            }
            this.InvokeAsync("GetDirectories", new object[] {
                        filePathLine,
                        additionalPath}, this.GetDirectoriesOperationCompleted, userState);
        }
        
        private void OnGetDirectoriesOperationCompleted(object arg) {
            if ((this.GetDirectoriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDirectoriesCompleted(this, new GetDirectoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.severfield.com/DirectoryExists", RequestNamespace="http://www.severfield.com/", ResponseNamespace="http://www.severfield.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DirectoryExists(int filePathLine, string additionalPath) {
            object[] results = this.Invoke("DirectoryExists", new object[] {
                        filePathLine,
                        additionalPath});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DirectoryExistsAsync(int filePathLine, string additionalPath) {
            this.DirectoryExistsAsync(filePathLine, additionalPath, null);
        }
        
        /// <remarks/>
        public void DirectoryExistsAsync(int filePathLine, string additionalPath, object userState) {
            if ((this.DirectoryExistsOperationCompleted == null)) {
                this.DirectoryExistsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDirectoryExistsOperationCompleted);
            }
            this.InvokeAsync("DirectoryExists", new object[] {
                        filePathLine,
                        additionalPath}, this.DirectoryExistsOperationCompleted, userState);
        }
        
        private void OnDirectoryExistsOperationCompleted(object arg) {
            if ((this.DirectoryExistsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DirectoryExistsCompleted(this, new DirectoryExistsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.severfield.com/GetDirectoryName", RequestNamespace="http://www.severfield.com/", ResponseNamespace="http://www.severfield.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDirectoryName(int filePathName, string additionalPath) {
            object[] results = this.Invoke("GetDirectoryName", new object[] {
                        filePathName,
                        additionalPath});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDirectoryNameAsync(int filePathName, string additionalPath) {
            this.GetDirectoryNameAsync(filePathName, additionalPath, null);
        }
        
        /// <remarks/>
        public void GetDirectoryNameAsync(int filePathName, string additionalPath, object userState) {
            if ((this.GetDirectoryNameOperationCompleted == null)) {
                this.GetDirectoryNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDirectoryNameOperationCompleted);
            }
            this.InvokeAsync("GetDirectoryName", new object[] {
                        filePathName,
                        additionalPath}, this.GetDirectoryNameOperationCompleted, userState);
        }
        
        private void OnGetDirectoryNameOperationCompleted(object arg) {
            if ((this.GetDirectoryNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDirectoryNameCompleted(this, new GetDirectoryNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.severfield.com/DirectoryGetFiles", RequestNamespace="http://www.severfield.com/", ResponseNamespace="http://www.severfield.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] DirectoryGetFiles(int filePathLine, string searchPattern, string additionalPath) {
            object[] results = this.Invoke("DirectoryGetFiles", new object[] {
                        filePathLine,
                        searchPattern,
                        additionalPath});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void DirectoryGetFilesAsync(int filePathLine, string searchPattern, string additionalPath) {
            this.DirectoryGetFilesAsync(filePathLine, searchPattern, additionalPath, null);
        }
        
        /// <remarks/>
        public void DirectoryGetFilesAsync(int filePathLine, string searchPattern, string additionalPath, object userState) {
            if ((this.DirectoryGetFilesOperationCompleted == null)) {
                this.DirectoryGetFilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDirectoryGetFilesOperationCompleted);
            }
            this.InvokeAsync("DirectoryGetFiles", new object[] {
                        filePathLine,
                        searchPattern,
                        additionalPath}, this.DirectoryGetFilesOperationCompleted, userState);
        }
        
        private void OnDirectoryGetFilesOperationCompleted(object arg) {
            if ((this.DirectoryGetFilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DirectoryGetFilesCompleted(this, new DirectoryGetFilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.severfield.com/CreateDirectory", RequestNamespace="http://www.severfield.com/", ResponseNamespace="http://www.severfield.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateDirectory(int fileLocation, string additionalPath) {
            this.Invoke("CreateDirectory", new object[] {
                        fileLocation,
                        additionalPath});
        }
        
        /// <remarks/>
        public void CreateDirectoryAsync(int fileLocation, string additionalPath) {
            this.CreateDirectoryAsync(fileLocation, additionalPath, null);
        }
        
        /// <remarks/>
        public void CreateDirectoryAsync(int fileLocation, string additionalPath, object userState) {
            if ((this.CreateDirectoryOperationCompleted == null)) {
                this.CreateDirectoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateDirectoryOperationCompleted);
            }
            this.InvokeAsync("CreateDirectory", new object[] {
                        fileLocation,
                        additionalPath}, this.CreateDirectoryOperationCompleted, userState);
        }
        
        private void OnCreateDirectoryOperationCompleted(object arg) {
            if ((this.CreateDirectoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateDirectoryCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.severfield.com/FileExists", RequestNamespace="http://www.severfield.com/", ResponseNamespace="http://www.severfield.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool FileExists(string fileToCheck, int filePathLine, string additionalPath) {
            object[] results = this.Invoke("FileExists", new object[] {
                        fileToCheck,
                        filePathLine,
                        additionalPath});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void FileExistsAsync(string fileToCheck, int filePathLine, string additionalPath) {
            this.FileExistsAsync(fileToCheck, filePathLine, additionalPath, null);
        }
        
        /// <remarks/>
        public void FileExistsAsync(string fileToCheck, int filePathLine, string additionalPath, object userState) {
            if ((this.FileExistsOperationCompleted == null)) {
                this.FileExistsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFileExistsOperationCompleted);
            }
            this.InvokeAsync("FileExists", new object[] {
                        fileToCheck,
                        filePathLine,
                        additionalPath}, this.FileExistsOperationCompleted, userState);
        }
        
        private void OnFileExistsOperationCompleted(object arg) {
            if ((this.FileExistsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FileExistsCompleted(this, new FileExistsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.severfield.com/CreateNewDirectory", RequestNamespace="http://www.severfield.com/", ResponseNamespace="http://www.severfield.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateNewDirectory(int fileLocation, string additionalPath) {
            this.Invoke("CreateNewDirectory", new object[] {
                        fileLocation,
                        additionalPath});
        }
        
        /// <remarks/>
        public void CreateNewDirectoryAsync(int fileLocation, string additionalPath) {
            this.CreateNewDirectoryAsync(fileLocation, additionalPath, null);
        }
        
        /// <remarks/>
        public void CreateNewDirectoryAsync(int fileLocation, string additionalPath, object userState) {
            if ((this.CreateNewDirectoryOperationCompleted == null)) {
                this.CreateNewDirectoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateNewDirectoryOperationCompleted);
            }
            this.InvokeAsync("CreateNewDirectory", new object[] {
                        fileLocation,
                        additionalPath}, this.CreateNewDirectoryOperationCompleted, userState);
        }
        
        private void OnCreateNewDirectoryOperationCompleted(object arg) {
            if ((this.CreateNewDirectoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateNewDirectoryCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.severfield.com/WriteToExcel", RequestNamespace="http://www.severfield.com/", ResponseNamespace="http://www.severfield.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool WriteToExcel(int filePathLine, int row, int col, string content, string additionalPath) {
            object[] results = this.Invoke("WriteToExcel", new object[] {
                        filePathLine,
                        row,
                        col,
                        content,
                        additionalPath});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void WriteToExcelAsync(int filePathLine, int row, int col, string content, string additionalPath) {
            this.WriteToExcelAsync(filePathLine, row, col, content, additionalPath, null);
        }
        
        /// <remarks/>
        public void WriteToExcelAsync(int filePathLine, int row, int col, string content, string additionalPath, object userState) {
            if ((this.WriteToExcelOperationCompleted == null)) {
                this.WriteToExcelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWriteToExcelOperationCompleted);
            }
            this.InvokeAsync("WriteToExcel", new object[] {
                        filePathLine,
                        row,
                        col,
                        content,
                        additionalPath}, this.WriteToExcelOperationCompleted, userState);
        }
        
        private void OnWriteToExcelOperationCompleted(object arg) {
            if ((this.WriteToExcelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WriteToExcelCompleted(this, new WriteToExcelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.severfield.com/ReadFromExcel", RequestNamespace="http://www.severfield.com/", ResponseNamespace="http://www.severfield.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReadFromExcel(int filePathLine, int row, int col, string addtionalLine) {
            object[] results = this.Invoke("ReadFromExcel", new object[] {
                        filePathLine,
                        row,
                        col,
                        addtionalLine});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReadFromExcelAsync(int filePathLine, int row, int col, string addtionalLine) {
            this.ReadFromExcelAsync(filePathLine, row, col, addtionalLine, null);
        }
        
        /// <remarks/>
        public void ReadFromExcelAsync(int filePathLine, int row, int col, string addtionalLine, object userState) {
            if ((this.ReadFromExcelOperationCompleted == null)) {
                this.ReadFromExcelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadFromExcelOperationCompleted);
            }
            this.InvokeAsync("ReadFromExcel", new object[] {
                        filePathLine,
                        row,
                        col,
                        addtionalLine}, this.ReadFromExcelOperationCompleted, userState);
        }
        
        private void OnReadFromExcelOperationCompleted(object arg) {
            if ((this.ReadFromExcelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadFromExcelCompleted(this, new ReadFromExcelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.severfield.com/WriteToExcelRange", RequestNamespace="http://www.severfield.com/", ResponseNamespace="http://www.severfield.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool WriteToExcelRange(int filePathLine, int startRow, int startCol, [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfAnyType")] [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)] object[][] content, string addtionalPath) {
            object[] results = this.Invoke("WriteToExcelRange", new object[] {
                        filePathLine,
                        startRow,
                        startCol,
                        content,
                        addtionalPath});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void WriteToExcelRangeAsync(int filePathLine, int startRow, int startCol, object[][] content, string addtionalPath) {
            this.WriteToExcelRangeAsync(filePathLine, startRow, startCol, content, addtionalPath, null);
        }
        
        /// <remarks/>
        public void WriteToExcelRangeAsync(int filePathLine, int startRow, int startCol, object[][] content, string addtionalPath, object userState) {
            if ((this.WriteToExcelRangeOperationCompleted == null)) {
                this.WriteToExcelRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWriteToExcelRangeOperationCompleted);
            }
            this.InvokeAsync("WriteToExcelRange", new object[] {
                        filePathLine,
                        startRow,
                        startCol,
                        content,
                        addtionalPath}, this.WriteToExcelRangeOperationCompleted, userState);
        }
        
        private void OnWriteToExcelRangeOperationCompleted(object arg) {
            if ((this.WriteToExcelRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WriteToExcelRangeCompleted(this, new WriteToExcelRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.severfield.com/ReadFromExcelRange", RequestNamespace="http://www.severfield.com/", ResponseNamespace="http://www.severfield.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfAnyType")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public object[][] ReadFromExcelRange(int filePathLine, int startRow, int startCol, int endRow, int endCol, string additionalPath) {
            object[] results = this.Invoke("ReadFromExcelRange", new object[] {
                        filePathLine,
                        startRow,
                        startCol,
                        endRow,
                        endCol,
                        additionalPath});
            return ((object[][])(results[0]));
        }
        
        /// <remarks/>
        public void ReadFromExcelRangeAsync(int filePathLine, int startRow, int startCol, int endRow, int endCol, string additionalPath) {
            this.ReadFromExcelRangeAsync(filePathLine, startRow, startCol, endRow, endCol, additionalPath, null);
        }
        
        /// <remarks/>
        public void ReadFromExcelRangeAsync(int filePathLine, int startRow, int startCol, int endRow, int endCol, string additionalPath, object userState) {
            if ((this.ReadFromExcelRangeOperationCompleted == null)) {
                this.ReadFromExcelRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadFromExcelRangeOperationCompleted);
            }
            this.InvokeAsync("ReadFromExcelRange", new object[] {
                        filePathLine,
                        startRow,
                        startCol,
                        endRow,
                        endCol,
                        additionalPath}, this.ReadFromExcelRangeOperationCompleted, userState);
        }
        
        private void OnReadFromExcelRangeOperationCompleted(object arg) {
            if ((this.ReadFromExcelRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadFromExcelRangeCompleted(this, new ReadFromExcelRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.severfield.com/CreateNewExcelSheet", RequestNamespace="http://www.severfield.com/", ResponseNamespace="http://www.severfield.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CreateNewExcelSheet(int filePathLine, string sheetName, string additionalPath) {
            object[] results = this.Invoke("CreateNewExcelSheet", new object[] {
                        filePathLine,
                        sheetName,
                        additionalPath});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CreateNewExcelSheetAsync(int filePathLine, string sheetName, string additionalPath) {
            this.CreateNewExcelSheetAsync(filePathLine, sheetName, additionalPath, null);
        }
        
        /// <remarks/>
        public void CreateNewExcelSheetAsync(int filePathLine, string sheetName, string additionalPath, object userState) {
            if ((this.CreateNewExcelSheetOperationCompleted == null)) {
                this.CreateNewExcelSheetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateNewExcelSheetOperationCompleted);
            }
            this.InvokeAsync("CreateNewExcelSheet", new object[] {
                        filePathLine,
                        sheetName,
                        additionalPath}, this.CreateNewExcelSheetOperationCompleted, userState);
        }
        
        private void OnCreateNewExcelSheetOperationCompleted(object arg) {
            if ((this.CreateNewExcelSheetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateNewExcelSheetCompleted(this, new CreateNewExcelSheetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.severfield.com/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.severfield.com/", IsNullable=false)]
    public partial class AuthHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        private string programNameField;
        
        private string programVersionField;
        
        private string domainNameField;
        
        private string externalKeyField;
        
        private string internalKeyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string ProgramName {
            get {
                return this.programNameField;
            }
            set {
                this.programNameField = value;
            }
        }
        
        /// <remarks/>
        public string ProgramVersion {
            get {
                return this.programVersionField;
            }
            set {
                this.programVersionField = value;
            }
        }
        
        /// <remarks/>
        public string DomainName {
            get {
                return this.domainNameField;
            }
            set {
                this.domainNameField = value;
            }
        }
        
        /// <remarks/>
        public string ExternalKey {
            get {
                return this.externalKeyField;
            }
            set {
                this.externalKeyField = value;
            }
        }
        
        /// <remarks/>
        public string InternalKey {
            get {
                return this.internalKeyField;
            }
            set {
                this.internalKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WriteToSpecificLineCompletedEventHandler(object sender, WriteToSpecificLineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WriteToSpecificLineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WriteToSpecificLineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WriteAllLinesWithArrayCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WriteAppendStringToFileCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WriteAppendStringsToFileCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ReadSpecificLineCompletedEventHandler(object sender, ReadSpecificLineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadSpecificLineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadSpecificLineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ReadAllLinesIntoArrayCompletedEventHandler(object sender, ReadAllLinesIntoArrayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadAllLinesIntoArrayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadAllLinesIntoArrayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetDirectoriesCompletedEventHandler(object sender, GetDirectoriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDirectoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDirectoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void DirectoryExistsCompletedEventHandler(object sender, DirectoryExistsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DirectoryExistsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DirectoryExistsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetDirectoryNameCompletedEventHandler(object sender, GetDirectoryNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDirectoryNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDirectoryNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void DirectoryGetFilesCompletedEventHandler(object sender, DirectoryGetFilesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DirectoryGetFilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DirectoryGetFilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CreateDirectoryCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void FileExistsCompletedEventHandler(object sender, FileExistsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FileExistsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FileExistsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CreateNewDirectoryCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WriteToExcelCompletedEventHandler(object sender, WriteToExcelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WriteToExcelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WriteToExcelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ReadFromExcelCompletedEventHandler(object sender, ReadFromExcelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadFromExcelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadFromExcelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void WriteToExcelRangeCompletedEventHandler(object sender, WriteToExcelRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WriteToExcelRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WriteToExcelRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ReadFromExcelRangeCompletedEventHandler(object sender, ReadFromExcelRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadFromExcelRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadFromExcelRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CreateNewExcelSheetCompletedEventHandler(object sender, CreateNewExcelSheetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateNewExcelSheetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateNewExcelSheetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591